"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar";
import { store } from "./redux/store";
import "./styles/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Shop- Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mainContainer">
        <Provider store={store}>
          <Navbar />
          <ToastContainer
            // toastStyle={{ backgroundColor: "#24a346", color: "white" }}
            autoClose={3000}
          />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
