// Product Types
export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";
export const FETCH_PRODUCT_LIST_BY_CATEGORY = "FETCH_PRODUCT_LIST_BY_CATEGORY";
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";

// Cart TYPES
export const FETCH_CART_PRODUCT_LIST = "FETCH_CART_PRODUCT_LIST";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";

// Category TYPES
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
